# Generated by Django 4.2.7 on 2023-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('calories', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
