# Generated by Django 4.2.7 on 2023-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=5)),
                ('reps', models.IntegerField(max_length=5)),
                ('sets', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
